updates

diff --git a/bin/janitor b/bin/janitor
--- a/bin/janitor
+++ b/bin/janitor
@@ -22,6 +22,13 @@ else
     echo "curl is already installed"
 fi
 
+if ! command -v brew &> /dev/null; then
+    echo "brew not found, installing..."
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+else
+    echo "brew is already installed"
+fi
+
 if ! command -v uv &> /dev/null; then
     echo "uv not found, installing..."
     curl -LsSf https://astral.sh/uv/install.sh | sh
